name: Add issues to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    if: github.event.pull_request.head.repo.full_name == github.repository  # Only run jobs if the feature branch is in your repo (not in a fork)
    runs-on: ubuntu-latest
    steps:
      - name: job step A
        run: |
          echo "run!"
